{
  modeConfig = "Train",
  parsingModeConfig = "Point",
  posModeConfig = False,
  grammarModeConfig = "CCG",
  epochConfig = 1,
  validationStepConfig = 400,
  batchSizeConfig = 16,
  actionEmbedSizeConfig = 256,
  wordEmbedSizeConfig = 256,
  hiddenSizeConfig = 256,
  numOfLayerConfig = 2,
  learningRateConfig = 1e-3,
  modelVersionConfig = "",
  resumeTrainingConfig = False,
  evalModelNameConfig = "rnng-CFG-pos-layer1-hidden128-epoch4-lr1.0e-2",
}