{
  modeConfig = "Train",
  parsingModeConfig = "Point",
  posModeConfig = False,
  grammarModeConfig = "CCG",
  epochConfig = 30,
  validationStepConfig = 400,
  actionEmbedSizeConfig = 128,
  wordEmbedSizeConfig = 128,
  hiddenSizeConfig = 128,
  numOfLayerConfig = 2,
  learningRateConfig = 1e-2,
  resumeTrainingConfig = True,
  modelVersionConfig = "composition",
  evalModelNameConfig = "rnng-CFG-pos-layer1-hidden128-epoch4-lr1.0e-2",
}