name:                rnng-hasktorch
version:             0.1.0.0
github:              "githubuser/rnng-hasktorch"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rnng-hasktorch#readme>

dependencies:
- base >= 4.7 && < 5
- text
- parsec
- optparse-applicative
- aeson
- bytestring
- yaml
- store
- juman-tools
- hasktorch
- hasktorch-tools
- containers
- filepath >= 1.4
- directory
- dhall
- projectroot
- split
- constraints
- gnuplot
- process

library:
  source-dirs: src

executables:
  Preprocessing:
    main:                Preprocessing.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Preprocessing
    dependencies:
    - rnng-hasktorch
  RNNG:
    main:                RNNG.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is RNNG
    dependencies:
    - rnng-hasktorch



tests:
  rnng-hasktorch-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rnng-hasktorch
